### ISSUE TITLE
beam search

### ISSUE THREAD

**Issue by lovodkin93** [EdinburghNLP/nematus#121]
Hey,
I would like to verify something in the Beam Search implementation:
Given I have a batch size of 3, and a beam search size of 4.
And for the sake of the example, let's say that the first "guess" for all the 3 batches is 1,2,3,4 , for beams 1,2,3,4 accordingly.
So The final "guessed words" vector should be ordered as [1,1,1,2,2,2,3,3,3,4,4,4], right?
Namely, we cluster together "beams" rather than "batches", correct?

**Comment by rsennrich** [comment]
can you be a bit more specific in your question? The beam search code ([beam_search_sampler.py](https://github.com/EdinburghNLP/nematus/blob/master/nematus/beam_search_sampler.py)) has multiple data structures of different shapes: some have `batch_size_x` as first dimension, others `beam_size`.
