### ISSUE TITLE
translation_maxlen

### ISSUE THREAD

**Issue by lovodkin93** [EdinburghNLP/nematus#122]
Hello,
so, something doesn't add up.
I defined translation_maxlen to be 100.
Now, I was going through the beam_search_sampler code, and it seems that sentences that are longer than 100 are still being translated. I know that in the training phase, sentences that are longer than maxlen are not being processed at all. Isn't it the same case for the inference phase with translation_maxlen? I am specifically talking about **source** language sentences that are longer than translation_maxlen.
Thanks!

**Comment by rsennrich** [comment]
--translation_maxlen controls the `Maximum length of translation output sentence`. There's currently no mechanism to exclude long source sentences from translation.

**Comment by lovodkin93** [comment]
great, thanks!
