### ISSUE TITLE
TypeError: param_init_embedding_layer() missing 2 required positional arguments: 'n_words' and 'dims

### ISSUE THREAD

**Issue by michael-brade** [EdinburghNLP/nematus#38]
I have been trying to get nematus to work using the wmt16 model, but I think there is something wrong in the code. I tried to fix it but no matter what I (guessed) to change, it keeps crashing in different places. Here's the root problem:
```
Warning: No built-in rules for language de.
Detokenizer Version $Revision: 4134 $
Language: de
Tokenizer Version 1.1
Language: en
Number of threads: 1
Translating <stdin> ...
Using cuDNN version 5110 on context None
Mapped name None to device cuda: GeForce GTX 960M (0000:01:00.0)
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/media/data/translation/nematus/nematus/translate.py", line 54, in translate_model
    f_init, f_next = build_sampler(tparams, option, use_noise, trng, return_alignment=return_alignment)
  File "/media/data/translation/nematus/nematus/nmt.py", line 359, in build_sampler
    x, ctx = build_encoder(tparams, options, trng, use_noise, x_mask=None, sampling=True)
  File "/media/data/translation/nematus/nematus/nmt.py", line 186, in build_encoder
    emb = get_layer_constr('embedding')(tparams, x, suffix='', factors= options['factors'])
TypeError: param_init_embedding_layer() missing 2 required positional arguments: 'n_words' and 'dims'
Error: translate worker process 10737 crashed with exitcode 1
```
If you look at `layers.py`, line 76, I think it's true. But where to get `n_words` and `dims` from?

**Comment by rsennrich** [comment]
Are you sure that your backtrace is with an unmodified version of 
Nematus? get_layer_constr('embedding') should return the function 
embedding_layer(), but for you, it seems to return the function 
param_init_embedding_layer(). The latter is called via 
get_layer_param('embedding'), for instance in line 91 in nmt.py, and you 
can see that both n_words and dims are provided to that function call.

**Comment by michael-brade** [comment]
Oh, excellent observation! Yes, the code is pretty much unmodified, except that I am using it with python 3.5 and had to adapt a few imports and the renamed `iteritems()`. The solution for my problem is this little typo:
```
--- a/nematus/layers.py
+++ b/nematus/layers.py
@@ -20,7 +20,7 @@ from alignment_util import *
 layers = {'ff': ('param_init_fflayer', 'fflayer'),
           'gru': ('param_init_gru', 'gru_layer'),
           'gru_cond': ('param_init_gru_cond', 'gru_cond_layer'),
-          'embedding': {'param_init_embedding_layer', 'embedding_layer'}
+          'embedding': ('param_init_embedding_layer', 'embedding_layer')
           }
```
note the difference of `{` vs `(`. I guess python 2.7 is less picky?! If you want, I can create a PR with all my python 3 changes.

**Comment by rsennrich** [comment]
thanks very much for spotting this, a patch is submitted.

Is your code backwards-compatible to Python 2? If so, I'm happy to also pull this in, but I don't want to sacrifice Python 2 compatibility.

**Comment by michael-brade** [comment]
Hm, no, apparently it is not. I can use `from __future__ import print_function` for the new print function, and only just now I found the `import six` library, so I don't know yet if that will be enough to make all of the other changes backwards-compatible. Plus, it will be an additional dependency - would that be ok?

**Comment by rsennrich** [comment]
I'd be ok with adding a dependency on six for the sake of cross-version 
compatibility.

**Comment by rsennrich** [comment]
Closing this. Python3 support is now in a branch, and will likely make its way into master soon.

**Comment by michael-brade** [comment]
Great! I still have the tab open as a TODO reminder, but I just won't have enough time until December. Guess I'll be able to close those tabs, too, then :)
