### ISSUE TITLE
infinite loop when there is a single token "|"

### ISSUE THREAD

**Issue by monsieurzhang** [EdinburghNLP/nematus#64]
Hi, 
I met this problem during decoding.
Since there is one sentence at WMT newstest13.fr:146
 "Soins palliatifs - La meilleure façon de mourir . . . | Le Devoir"

Could you confirm that? Thanks.

https://github.com/EdinburghNLP/nematus/blob/c4adba6cd545e5d7048ea5512d5bee712bd0c9b9/nematus/translate.py#L388

**Comment by rsennrich** [comment]
"|" is normally reserved as factor separator, but I've now added a condition to translate.py so that "|" in the input will be accepted if you don't use factored models.
