### ISSUE TITLE
we train Neural Machine Translation (NMT) models in both direction using Nematus

### ISSUE THREAD

**Issue by bhagat02** [EdinburghNLP/nematus#66]
Hi,
I was reading your paper "A Parallel Corpus of Python Functions and Documentation Strings for
Automated Code Documentation and Code Generation" where you have told that you have trained "Neural Machine Translation (NMT) models in both direction using Nematus" 

my question is how to preprocess the dataset as the dataset is a parallel corpus of python funtion and doc strings.
for ex- if we use a parallel corpora of only text like eng-deu , we use word embeddings. so , in this case what we will use ?
Thank you so much

**Comment by bhagat02** [comment]
Thank you so much for your reply but i wanted to ask you do we use
embedding layer before a bidirectional RN encoder for converting code to
doc-strings?

**Comment by bricksdont** [comment]
Yes, absolutely.

**Comment by bhagat02** [comment]
Thank you so much for your reply.
