### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [EdinburghNLP/nematus#68]
Hello, I would like to collaborate with the Spanish translation, is it done?

**Comment by bricksdont** [comment]
Hi,

Your question is a bit unclear. Nematus is not a system for specific languages; it is meant to support translation from and to any language. That said, different languages will require different kinds of preprocessing.

**Comment by dbucci24** [comment]
So, is there something I can collaborate with in Spanish?

**Comment by bricksdont** [comment]
As I said, no part of Nematus is specific to Spanish, except some of the preprocessing scripts:

https://github.com/EdinburghNLP/nematus/tree/master/data

that are mostly borrowed from the Moses project. If that does not answer your question, please try to ask it differently.
