### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by bhagat02** [EdinburghNLP/nematus#69]
hi ,
can u please tell me what is the algorithm of you neural machine translator. what all steps you have done to make it so different from other neural machine translator .
So, i request you to please tell me the algorithm.

best,
Bhagat

**Comment by bhagat02** [comment]
And why you choosed theano over tensorflow or keras?

**Comment by rsennrich** [comment]
you will find a general description of the algorithm in the Nematus 
paper: http://aclweb.org/anthology/E17-3017.pdf

another description of the network architecture is here: 
https://github.com/marian-nmt/marian/blob/master/contrib/notebooks/dl4mt.ipynb

**Comment by rsennrich** [comment]
The theano code in Nematus predates the release of tensorflow; there is 
now a tensorflow branch here: 
https://github.com/EdinburghNLP/nematus/tree/tensorflow

**Comment by bhagat02** [comment]
Dear Sennrich,

Thank you so much .



Best Regards,
Gaurav Bhagat
