### ISSUE TITLE
EOFError in ERROR: test_ende (__main__.TestTranslate)

### ISSUE THREAD

**Issue by Ryanight** [EdinburghNLP/nematus#71]
I'm a beginner in NMT. I got an error when I try to run the `test_traslate.py` with the script: `THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=cpu python test_translate.py` 

The feedback was:
![1522250383082](https://user-images.githubusercontent.com/24364345/38038835-8254e408-32de-11e8-954b-1646ffb414d5.jpg)

It will be great if you can help with my problem. Thanks a lot!

**Comment by bricksdont** [comment]
Hi,

Can you please tell us what you are trying to do? Currently, you are running a unit test - which is not about training or translating as such.

**Comment by Ryanight** [comment]
I'm sorry I didn't quite understand what should I do to run a test. I was using the `README` in the test folder step by step. Was I wrong in running the test?

**Comment by bricksdont** [comment]
It's not wrong to run a test, I was just trying to find out whether your actual goal is to run the tests, or if it is training, or translation with a trained model.

Do you have a working internet connection? The first time you are running this test it attempts to download models.

**Comment by rsennrich** [comment]
try deleting the "test/models" directory, and run the script again. You most likely have a corrupted download of the model files.
