### ISSUE TITLE
little guidance required

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#72]
hey, if i want to use NEMATUS for code2doc task how to use it . Can u please guide me with the steps.Thank you so much.
I have already done all the preprocessing tast as suggested by you . now i am not able to get it that how to use the vocab file .json file and the x.train , y.train.

**Comment by cshanbo** [comment]
Nematus is basically a neural machine translation system.
Following the [test_train.sh](https://github.com/EdinburghNLP/nematus/blob/master/test/test_train.sh) could help

**Comment by rsennrich** [comment]
I added the command-line documentation to the README again. I also suggest you look at the scripts in http://data.statmt.org/wmt17_systems/training/ for suggested parameter settings.

**Comment by jigyasa06** [comment]
thank you so much and i also want to know what this command
OrderedDict(sorted(vars(config).items()))
 is actually doing i was trying to re-implement it using 
config = OrderedDict(sorted(FLAGS.__flags.items())) for code2doc
(rather than using config i am using FLAG else everything is same , can you give any suggestions?
 but it was giving me an error :
unsupported operand type(s) for -: 'float' and 'Flag'

Thank you so much once again it really means a lot. your guidance is superb.i follow u.
:)

**Comment by bricksdont** [comment]
OrderedDict(sorted(vars(config).items()))

means to extract the keys and values from `config` (e.g. an `argparse.Namespace` object) as a dict, then sort them and fix their order.

But why are you using flags in the first place? Also, you did not give much context. Could you perhaps link to your forked repository?
