### ISSUE TITLE
translate.py

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#79]
hi i want to knwo that i ran my training till 350 epochs an i got these models :+1: 
model.npz-30000.data-00000-of-00001  model.npz.index        
model.npz-30000.index                model.npz.json          
model.npz-30000.meta                 model.npz.meta          
model.json  model.npz-30000.progress.json        model.npz.progress.json
model.npz   model.npz.data-00000-of-00001  

Then i ran the command ~/data/nematus-master# python nematus/score.py --models model model.npz model.npz.progress  model.npz-30000.meta model.npz-30000.progress  --source /root/data/nematus-master/data2/test/decldesc_test_bpe --target /root/data/nematus-master/data2/test/bodies_test_bpe --output /root/data/nematus-master/data2/test/output2.txt

and  i got an error 
Traceback (most recent call last):
  File "nematus/score.py", line 82, in <module>
    main(source_file, target_file, output_file, scorer_settings)
  File "nematus/score.py", line 68, in main
    fill_options(options[-1])
  File "/root/data/nematus-master/nematus/compat.py", line 19, in fill_options
    first_factor_size = options['n_words_src']
**KeyError: u'n_words_src'**

can you please tell me why this eror is coming . please guide me where i am going wrong.

**Comment by rsennrich** [comment]
Hello,

it is sufficient to specify one model (typically the one with the best 
validation loss, which is stored in model.npz):

~/data/nematus-master# python nematus/score.py --models model.npz 
--source /root/data/nematus-master/data2/test/decldesc_test_bpe --target 
/root/data/nematus-master/data2/test/bodies_test_bpe --output 
/root/data/nematus-master/data2/test/output2.txt

your error comes from Nematus trying to read (and "fix") a json file 
that is actually not storing model options, but other info (my guess is 
on "model.npz.progress.json").

best wishes,
Rico

**Comment by jigyasa06** [comment]
i am using the same tensorflow version 1.8.0 for both saving and restoring the model still the error is coming.

**Comment by jigyasa06** [comment]
hey can you please help me with this . I am waiting for your reply.

thank you so much.

**Comment by pjwilliams** [comment]
Hi, is model.npz the model that you trained yourself? Could you please provide the full commands that you used for training the model and for running translate.py?

Best wishes,
Phil

**Comment by jigyasa06** [comment]
the command which i wrote for training is :

 jigyasa$ python nmt.py --source_dataset /Users/jigyasa/Desktop/thesis/code_generation_bpefiles/train/decldesc_train_bpe --target_dataset /Users/jigyasa/Desktop/thesis/code_generation_bpefiles/train/bodies_train_bpe --dictionaries /Users/jigyasa/Desktop/thesis/dataset_for_my_thesis/code_generation_nmt_dictionary/train/decldesc_train_bpe.json /Users/jigyasa/Desktop/thesis/dataset_for_my_thesis/code_generation_nmt_dictionary/train/bodies_train_bpe.json --valid_datasets /Users/jigyasa/Desktop/thesis/code_generation_bpefiles/validate/decldesc_valid_bpe /Users/jigyasa/Desktop/thesis/code_generation_bpefiles/validate/bodies_valid_bpe --model /Users/Jigyasa/Desktop/model.npz --max_epochs 350

i just created a file with touch command and named it as model.npz and i gave the path of this file as shown above

**Comment by bricksdont** [comment]
`touch` creates an empty file. If you created an empty file named `model.npz`: why?

**Comment by jigyasa06** [comment]
hi @pjwilliams thank you so much for your reply this means a lot. Actually firstly i did my training without giving any model but after some epochs around 200 maybe the error came that the model cannot store .. the model path not found. like that ... that is why i gave the model name  model.npz with a path .


these two commands I added afterwards .. due to some errors.. 

--model /Users/Jigyasa/Desktop/model.npz --max_epochs 350

now as you suggest should I train the model again and without these two commands ?

**Comment by pjwilliams** [comment]
You should remove the --max_epochs argument but keep the --model one. The model argument should be OK, provided that /Users/Jigyasa/Desktop is an existing directory and that you have permission to write files there. If the error keeps happening, could you please send the complete error message?

Best wishes,
Phil

**Comment by jigyasa06** [comment]
Thank you so much for your reply . As suggested by you i have run the desired command and now my training has started once again . I hope this time I don't get any error, but if I will get any I will update you once again regarding that.

Thank you so much once again @pjwilliams for your support and guidance , This means a lot.

Best Regards,
Jigyasa Sakhuja

**Comment by jigyasa06** [comment]
hey @pjwilliams @rsennrich I have been training this model on code documentation dataset since past 6 days and I have reached only till 181 epochs and the last recent info was this.

INFO: [2018-08-08 16:46:23] Epoch: 177 Update: 25000 Loss/word: 1.57721595451 Words/sec: 170.468366283 Sents/sec: 3.5156388417

So, I want to know how much time the training can take because it is taking a lot of time .
and also is there any faster way to do the training . If yes please suggest as I have not even set the number of epochs as you told not do give any number of epochs while training this model.

Thank you once again. Waiting for your reply. :)
Best Regards,
Jigyasa Sakhuja

**Comment by pjwilliams** [comment]
3.5 sents/sec is very slow. Are you using a GPU or running this on the CPU?

Best wishes,
Phil

**Comment by jigyasa06** [comment]
Hey Phil ,

I do not have a GPU so i am basically running it on a CPU only . But it is
taking a lot of time.

Can you please suggest me anything .

Thank you
Best regards,
Jigyasa Sakhuja

**Comment by pjwilliams** [comment]
Hi Jigyasa,

I don't recommend using Nematus to train on a CPU unless your model is very small. if you don't have access to a machine with a GPU, then it may be worth taking a look at Marian, which has some CPU-specific optimisation (although it is still significantly slower than using a GPU): https://marian-nmt.github.io <https://marian-nmt.github.io/> 

Best wishes,
Phil

**Comment by jigyasa06** [comment]
hey,
 I got the GPU access now and i really want to know how to run nmt.py on GPU.

I triend once myself but i failed 
<img width="563" alt="screen shot 2018-08-13 at 21 34 10" src="https://user-images.githubusercontent.com/37703929/44053763-e86139e4-9f40-11e8-8cfd-dbeed153e2af.png">

I am not able to access the docker file as it is always showing permission denied as I am using my university GPU.

so, please guide me @pjwilliams @rsennrich 

Thanks a lot .

Best Regards,
Jigyasa Sakhuja

**Comment by jigyasa06** [comment]
Hey i got the GPU access and I am running the Code on it 👍 . I hope it works for me now.

**Comment by jigyasa06** [comment]
<img width="571" alt="screen shot 2018-08-18 at 14 04 15" src="https://user-images.githubusercontent.com/37703929/44299104-d9d07180-a2ef-11e8-93d2-7f1de84fbcd8.png">
hey after training it by gpu i got this message regarding early stop . I want to know is the training successfull or not?

**Comment by pjwilliams** [comment]
Hi, yes, that message means that training has ended because the validation loss has stopped improving.

The validation loss looks rather high - values of less than 100 are more typical, though it depends on many factors. Is your training data very different from the validation set?

Best wishes,
Phil

**Comment by jigyasa06** [comment]
i am working on code generation dataset (code-docstring-corpusp)rovided by @rsennrich in automated python code generation and code documentation . I Have not generated my own dataset.
Please tell me is the dataset alryt? @rsennrich @pjwilliams 
best regards,
Jigyasa Sakhuja

**Comment by rsennrich** [comment]
automatic code generation / documentation is more difficult than translation, so the high validation loss is no big surprise. Maybe @Avmb has his own numbers for comparison.

**Comment by jigyasa06** [comment]
okay @rsennrich thank you for your guidance

**Comment by jigyasa06** [comment]
hi @pjwilliams  @rsennrich  as i told you that i am done with my training but i am not able to run translate.py. whenever i run it i get an error as nematus creates a lot of model and we have to take the model with the best validation loss .

so can you please guide me how to actually go forward with this:
<img width="537" alt="screen shot 2018-08-31 at 17 44 32" src="https://user-images.githubusercontent.com/37703929/44922377-917c6f00-ad45-11e8-8029-62a7f3719f5f.png">
these were the models which i got after the training and i did my training as you told . Now please can you tell me how to proceed further because when i am giving this command it is giving me an error
<img width="563" alt="screen shot 2018-08-31 at 17 46 13" src="https://user-images.githubusercontent.com/37703929/44922516-d1435680-ad45-11e8-8b75-fb9eefc2b985.png">

**Comment by jigyasa06** [comment]
<img width="567" alt="screen shot 2018-08-31 at 17 58 20" src="https://user-images.githubusercontent.com/37703929/44923088-7f033500-ad47-11e8-8992-de116898962b.png"
and when i gave my model as nematus it was running and i got this error ::

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "nematus/translate.py", line 150, in _start_worker
    output_item = self._translate(process_id, input_item, models, sess)
  File "nematus/translate.py", line 166, in _translate
    x, x_mask, _, _ = prepare_data(x, y_dummy, maxlen=None)
  File "/home/sakhuja/jigyasa_project/nematus-master/nematus/util.py", line 36, in prepare_data
    n_factors = len(seqs_x[0][0])
IndexError: list index out of range
ERROR: Translate worker process 14340 crashed with exitcode 1

I do not know where i am going wrong can you please guide me @rsennrich @pjwilliams @Avmb

**Comment by jigyasa06** [comment]
@rsennrich @pjwilliams @Avmb can you please guide .

**Comment by pjwilliams** [comment]
Does your input file contain any blank lines? It looks like Nematus does not handle these properly.

Phil

**Comment by jigyasa06** [comment]
hi @pjwilliams i have taken the dataset of @Avmb and i have done the tokenization and Byte pair encoding  of @rsennrich than i generated the datasets. I really want to know in the input and output what files we need to specify and what we need to specify in the -model as so many models are generated.

**Comment by rsennrich** [comment]
your command looks fine; like Phil mentioned, translate.py would crash if empty lines are input, but this is now fixed in commit 3d97d78dfbd7fcadeca530c5ab5dc6da026218e8.

Note that, if you don't see any empty lines during training, the model won't necessarily learn what to do if it encounters empty input at test time.

**Comment by jigyasa06** [comment]
<img width="570" alt="screen shot 2018-09-07 at 12 33 30" src="https://user-images.githubusercontent.com/37703929/45214277-4c52c280-b29a-11e8-844b-67662459c89d.png"
thank you for your updates @rsennrich after doing this i got this attribute error.Can you please see to it

**Comment by pjwilliams** [comment]
That's a strange error. It looks like two of your Nematus source files (translate.py and settings.py) are out of sync. Are you using the latest version of the Nematus code? Have you made any modifications to the code?

**Comment by jigyasa06** [comment]
@pjwilliams yes i made the modification as @rsennrich told me. According to that commit which he has shown me.So i have updated my translate.py file , util.py and nmt.py according to his before comment.

and i just tried to run another file score.py i got this result but nothing came in my output.txt file , it was blank
<img width="562" alt="screen shot 2018-09-07 at 12 56 22" src="https://user-images.githubusercontent.com/37703929/45215507-ec5e1b00-b29d-11e8-91ea-2a463d6ddf21.png">

**Comment by pjwilliams** [comment]
You need to pull the latest commits (using a git command like "git pull origin master"). You shouldn't be manually updating individual files. I would suggest creating a fresh clone of the repository and trying again with that.

Phil

**Comment by jigyasa06** [comment]
okay thank you so much :) i am doing that only now

**Comment by jigyasa06** [comment]
hey @pjwilliams and @rsennrich  I want to ask in translate.py in input and output what file we need to give ? i gave in input the test file of declation and description and i gave the bodies as output but i think this is not correct because in the ouput  we will get the translations. So, can you please guide a little bit.

**Comment by rsennrich** [comment]
"--output" is the file path that you want to write to. The right "--input" depends on what type of translation system you trained: it should be the same type of text that you had on the source side at training time, preprocessed in the same way.

**Comment by jigyasa06** [comment]
okay thank you so much :)

**Comment by jigyasa06** [comment]
In score.py file i am getting the ouput for every sentence. For e.g. i am getting score like this 
<img width="629" alt="screen shot 2018-09-30 at 19 43 43" src="https://user-images.githubusercontent.com/37703929/46260655-2ad7a600-c4e9-11e8-9e56-70734584aa09.png">
But my question is how to know about the result?

**Comment by jigyasa06** [comment]
i want to know about the score of the translation.. for ex BLEU score. So, that i can see what  is the result .. output i mean

**Comment by pjwilliams** [comment]
score.py scores source and target sentence pairs according to the model, which is not what you are looking for. To get a BLEU score you can use Nematus' multi-bleu-detok.perl. For an example of how to use it, see this script:

https://github.com/EdinburghNLP/wmt17-scripts/blob/master/training/scripts.tensorflow/evaluate.sh <https://github.com/EdinburghNLP/wmt17-scripts/blob/master/training/scripts.tensorflow/evaluate.sh>

Best wishes,
Phil

**Comment by jigyasa06** [comment]
Thank you so much for helping. :) @pjwilliams

**Comment by jigyasa06** [comment]
@pjwilliams in score.py file how is the scoring actually done? for ex: if i am getting score 231 for a line then what it means ? As you can see the result in output_score.txt

**Comment by pjwilliams** [comment]
The score is the sentence-level cross-entropy. If you give the -n option to score.py, then the score will be normalized (i.e. divided by the length of the target sentence to give an average). You should see one score for each pair of sentences in the source / target input files.

**Comment by pjwilliams** [comment]
Essentially, it's a sum of negative log probabilities, so it's the other way round: lower is better.

**Comment by jigyasa06** [comment]
okay thank you so much :)
