### ISSUE TITLE
BLUE score

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#86]
HI @pjwilliams I wanted to know one last thing regarding the BLUE score, that in this what file i will give as the candidate file and what file will be the reference file?

I think reference file will be my original test file and candidate file will be the file created by the model?

**Comment by pjwilliams** [comment]
The candidate file should be the translations from Nematus, after you have applied any postprocessing (e.g. to merge BPE subword units into words). The reference file should be the target-side file from your test set.

Best wishes,
Phil
