### ISSUE TITLE
Post processing

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#87]
Can you please give me the link for post processing of the bpe files. So that i can get the BLUE score @pjwilliams . Thank you once again.

Do you mean by this : sed -r 's/(@@ )|(@@ ?$)//g'

**Comment by pjwilliams** [comment]
Yes, that sed command will merge BPE subwords. If the only preprocessing you did was to split the input text into BPE subwords, then that's all you need to do in your postprocessing step.

**Comment by jigyasa06** [comment]
but how to actually use this command .. there is no such usage direction. Like how shoukd i input my candidate file into this?? 
@pjwilliams

**Comment by pjwilliams** [comment]
Here is a tutorial about using sed. It should tell you what you need to know: https://linuxconfig.org/learning-linux-commands-sed

**Comment by jigyasa06** [comment]
@pjwilliams thank you so much

**Comment by rsennrich** [comment]
In the future, please use Nematus support ( https://groups.google.com/d/forum/nematus-support ) for general support requests, and reserve Github issues for reporting bugs.

**Comment by jigyasa06** [comment]
okay @rsennrich thank you for the information. I just need to confirm this. Why is it coming like this? 
sed -r 's/(@@ )|(@@ ?$)//g'
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...
@pjwilliams .
Thank you once again for your help and support
