### ISSUE TITLE
Code  generation and code documentation

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#90]
Hi ,
I actually want to know that in the pre-processing of code generation and code documentation you have used DCNL DSCP etc to preprocess the python code. I want to know why? and what was your actual goal?

Isn't the derived syntax became very complicated for the human being to understand ? @rsennrich  @Avmb  

Best Regards,
Jigyasa Sakhuja

**Comment by jigyasa06** [comment]
can you give me any answer regarding my question if possible ? @rsennrich @Avmb because in your paper nowhere it is mentioned regarding this.

**Comment by rsennrich** [comment]
please use proper communication channels. This is not a Nematus issue.
