### ISSUE TITLE
MRT in TensorFlow version

### ISSUE THREAD

**Issue by felicitywang** [EdinburghNLP/nematus#94]
Hi,
Is there or will there MRT support in the TensorFlow version? I've been using the Theano version for MRT but assume the TensorFlow version might be faster with newer features?
Thanks!

**Comment by rsennrich** [comment]
There is currently no MRT support in TensorFlow Nematus. It's not our highest priority, but we're happy if somebody volunteers to implement it - some code (like the metrics) can be reused from the Theano version, and is actually still there.
