### ISSUE TITLE
multiple models (with same vocabulary) for ensemble decoding

### ISSUE THREAD

**Issue by cong1** [EdinburghNLP/nematus#95]
Hi, I want to use an multiple model to translate a source text.But I am not sure what its order is.

device=gpu2
nematus=/media/ntfs-1/nematus-theano

THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=$device,on_unused_input=warn python $nematus/nematus/nematus/translate.py \
     -m $nematus/model/model.npz\
     -i $nematus/wmt16-scripts/sample/datatest/test2.bpe.ro \
     -o $nematus/wmt16-scripts/sample/datatest/ensemblepred2.en \
     -k 12 -n -p 1

**Comment by rsennrich** [comment]
-m takes multiple arguments, so you can do something like this:

 -m $nematus/model/model1.npz $nematus/model/model2.npz

**Comment by cong1** [comment]
Thank you, the problem has been solved.
