### ISSUE TITLE
Question about running on GPU

### ISSUE THREAD

**Issue by ariter777** [EdinburghNLP/nematus#98]
To illustrate what I'm talking about: when training an acoustic model and a duration model with Merlin using Theano, using a GPU, the resulting models can only be used when run on a GPU – GPU-made models are incompatible with CPU's, and I guess that it's also true the other way around.

To put it simply, does that issue exist with Nematus using Theano? Or can I just train a model on a GPU relatively fast, and then actually use it on a CPU?

(Yup, I know that Merlin and Nematus are apples and oranges, but they both have the option of using Theano, so that's why I'm asking)

**Comment by bricksdont** [comment]
Nematus-Theano models should always run both on CPU and GPU. Also, not running models on CPU seems a very strange "feature" of Merlin.

But more importantly: is there any reason why you are not using a newer version of Nematus built with Tensorflow?

**Comment by ariter777** [comment]
Oh, I'm just more familiar with Theano, so I thought I'd start out with the Theano version and graduate to Tensorflow when I had it down. 

Anyways, when you say that the Nematus-Theano models should always run on both CPU and GPU – does that mean that it'd be impossible to train a model on a powerful GPU, to save time, and then run it only on CPU for decoding/encoding?

**Comment by bricksdont** [comment]
The reason I am bringing up Theano vs. Tensorflow is that the development of Theano was discontinued. There will not be any new updates and over time, problems will accumulate if Theano is used on newer platforms.

>Anyways, when you say that the Nematus-Theano models should always run on both CPU and GPU – does that mean that it'd be impossible to train a model on a powerful GPU, to save time, and then run it only on CPU for decoding/encoding?

No, I meant the exact opposite. It should always be possible to use either (meaning: just one of them). Small caveat to keep in mind: Processes on GPU are always controlled by CPU processes, so there will be load on CPU too if a training runs on GPU.
